name: Check profiles

on:
  pull_request:
    branches:
      - main
    paths:
      - 'resources/profiles/**'
      - '.github/workflows/check_profiles.yml'

  workflow_dispatch:

jobs:
  check_profiles:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download validator
        run: |
          curl -LJO https://github.com/SoftFever/Orca_tools/releases/download/1/OrcaSlicer_profile_validator
          chmod +x ./OrcaSlicer_profile_validator

      - name: Run validation for each profile version
        run: |
          echo "Validating profiles in ./resources/profiles/"
          python3 ./scripts/orca_extra_profile_check.py
          ./OrcaSlicer_profile_validator -p ./resources/profiles/ -l 2

      - name: Check profile version bump
        if: github.event_name == 'pull_request'
        run: |
          python3 ./scripts/check_profile_version_bump.py --base origin/${{ github.base_ref }}
