name: Check Notarization Status

on:
  workflow_dispatch:
    inputs:
      submission_id:
        description: "Submission ID da controllare"
        required: true

jobs:
  check-status:
    runs-on: macos-latest

    steps:
      - name: Store credentials in temporary keychain profile
        run: |
          xcrun notarytool store-credentials "ci-profile" \
            --apple-id "${{ secrets.APPLE_ID }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" \
            --password "${{ secrets.APPLE_APP_PASSWORD }}"

      - name: Check notarization status
        run: |
          xcrun notarytool status \
            ${{ github.event.inputs.submission_id }} \
            --keychain-profile "ci-profile" \
            --output-format json
